### ISSUE TITLE
Integration with Angular Animations

### ISSUE THREAD

**Issue by blittle** [Hill30/NGScroller#12]
I have been looking over the source and am wondering if there is any plan to integrate NGScroller with angular animations, or at least maybe a limited form?

**Comment by cnickless** [comment]
+1 for ngAnimate integration

**Comment by maximelebreton** [comment]
+1

**Comment by mfeingold** [comment]
we have an (experimental) version supporting animation in the animation branch. Have a look [here](http://rawgit.com/Hill30/NGScroller/animation/src/examples/adapter2.html).

**Comment by mfeingold** [comment]
Just renamed the animation example in the branch [here](http://rawgit.com/Hill30/NGScroller/animation/src/examples/animation.html)

**Comment by blittle** [comment]
@mfeingold :+1: excited to see this roll into a release!

**Comment by maximelebreton** [comment]
@mfeingold  cool!
