### ISSUE TITLE
Starting the scroll at the end of the data?

### ISSUE THREAD

**Issue by lmessinger** [Hill30/NGScroller#67]
Hi

I wonder if ngInfiniteScroll support starting on different positions?

thanks
Lior

**Comment by mfeingold** [comment]
This functionality can be easily implemented by adjusting the logic of the datasource get method, namely by changing how indexes supplied to the get call are mapped to the underlying dataset item indexes.  For an example look [here](http://rawgit.com/Hill30/NGScroller/master/src/examples/persistentScroll.html), specifically look at how the offset in the url is used
