### ISSUE TITLE
Race condition between manipulation methods and load process

### ISSUE THREAD

**Issue by mfeingold** [Hill30/NGScroller#70]
What happens if a manipulation method is called while there are pending requests?

**Comment by nbrookie** [comment]
:+1: I am running into this issue right now, and I am trying to come up with a solution. I will let you know what I find (hopefully it will be helpful :smile: )

**Comment by mfeingold** [comment]
@nbrookie:  Incrementing revision id (line 439 in https://github.com/Hill30/NGScroller/blob/master/src/scripts/ui-scroll.coffee) was supposed to take care of this. It would cause the results of the outstanding requests to be discarded. Did it not help in your case?

**Comment by mfeingold** [comment]
@dhilt check this out

**Comment by dhilt** [comment]
The potential problem is that we did not clean the pending array and did increment the ridActual when applyUpdates() happens during reload() processing. 

![scroller pending problem](https://cloud.githubusercontent.com/assets/4365660/8502042/2fd0adae-21b4-11e5-8f98-c6a71e06a842.png)
