### ISSUE TITLE
Update with adapter (V.1.1.1)

### ISSUE THREAD

**Issue by jcstritt** [Hill30/NGScroller#75]
I check your examples (adapter and adapter2.coffee, diff ?) with version 1.1.1 and try to update a customer object with a similar code, but update never applies on screen (ok in DB, made before the call to "applyUpdates"). Have you any idea what i made false ? Delete is ok with the return of []. Thanks for you answer.

    return vm.adapter.applyUpdates(function (item, scope) {
       if (item.pkItem === updatedItem.pkItem) {
         item =  updatedItem;
       }
     });

tested too : return updatedItem or return [updatedItem]

**Comment by mfeingold** [comment]
According to the documentation the updater function is supposed to return an array of items you want to be inserted in place of the item passed to it as a parameter. If the return value of the function is not an array, the original item stays where it was. You still can make changes to the item properties and they will be reflected in the content.
So to change your code:

    return vm.adapter.applyUpdates(function (item, scope) {
       if (item.pkItem === updatedItem.pkItem) {
         return  [updatedItem];
       }
     });

or

    return vm.adapter.applyUpdates(function (item, scope) {
       if (item.pkItem === updatedItem.pkItem) {
         item.something =  updatedItem.something;
       }
     });

**Comment by jcstritt** [comment]
Ok, I have tried your two solutions (thanks for that). It works the two, but It seems that there is a bug when updating the first item in the list and there is no DOM element above (with 0 or smaller index). The return of [updatedItem] delete temporarily the first index=1 entry ! After, if there is some DOM element above (but hidded), all is ok, i can update any entry. Can you confirm or infirm ?

**Comment by mfeingold** [comment]
Yea, I can confirm this is a bug. I fixed it in the latest commit. As a side note no matter what you using index based updates is difficult, because indexes of the items are not stable. It is much better to use the second version of applyUpdates where you can use your knowledge of what's the item to identify the one(s) you would like to update

**Comment by jcstritt** [comment]
Thanks for your answer. I try the last commit but I have the same issue (first entry not updated, but deleted). Why this is not V1.1.2 ? And why have you created a new bug issue for that ? Is this not yet corrected in last commit ? Otherwise, I don't understand why the second example is better ? When a user change N fields in view, we must loop on each property ("something") to update ? Sorry for all my questions !

**Comment by mfeingold** [comment]
I am somewhat confused about what exactly you are trying to do. Can you post a repro? either [plunk](http://plnkr.co/) or [jsfiddle](https://jsfiddle.net/) would do just fine.

**Comment by jcstritt** [comment]
I want only update some of fields of an object-entity in a row (perhaps "Créanciers" to "Créanciers2" and an amount of 150'800.00  to 150'900.00 for example). The view-update of fields is made with an popup dialog box called with the blue button at the right here :
![image](https://cloud.githubusercontent.com/assets/6073801/6644121/efb4e8e8-c9b1-11e4-93b3-cdd0e339fdda.png)

The result : **First row with idx=1 is deleted first time when I update with this code :**

    return vm.adapter.applyUpdates(function (item, scope) {
            if (item && item.pkEcriture === updatedItem.pkEcriture) {
              return [updatedItem];
            }
          }); 

![image](https://cloud.githubusercontent.com/assets/6073801/6644202/723013ec-c9b2-11e4-8932-4c2339476421.png)

I have too many dependences to made a simple plunkr for the moment. But, I will try.

**Comment by mfeingold** [comment]
When you return a new item, such item replaces the old one. Specifically, it is inserted after the old one and then the old one is deleted. This use case is covered by a unit test (see line 290 or line 1012 of [ScrollerSpec.js](https://github.com/Hill30/NGScroller/blob/master/test/ScrollerSpec.js) for an example). If for some reason it does not work in your case, I cannot see a reason without more details. 

An alternative would be not to replace the item at all. Just change the values on the existing item like in 1012 of [ScrollerSpec.js](https://github.com/Hill30/NGScroller/blob/master/test/ScrollerSpec.js);

**Comment by jcstritt** [comment]
Ok this work (solution 2) :

           return vm.adapter.applyUpdates(function (item, scope) {
            if (item && item.pkEcriture === updatedItem.pkEcriture) {
              for (var property in updatedItem) {
                if (updatedItem.hasOwnProperty(property) && (typeof updatedItem[property]) !== 'function') {
                  item[property] = updatedItem[property];
                }
              }
              //return [updatedItem];
            }
          });  

Thanks for your help

**Comment by mfeingold** [comment]
@jcstritt: That's good news. Thank you for your patience. I am still curious though why your original solution did not work. Any chance you can provide me with any additional information? Might be I am missing another bug here.

From the standpoint of the solution the one you have right now is a better one - because the actual item is not replaced, only its properties, it minimizes the churn of the DOM element updates

**Comment by jcstritt** [comment]
The second solution is a bit more verbose, but works well with my server data. I think there is still a bug with the first solution, but I have no more time to waste on tests. Thank you for everything.
