### ISSUE TITLE
adapter and inserting elements

### ISSUE THREAD

**Issue by Madd0g** [Hill30/NGScroller#77]
Hi, great library.

I wrote a caching helper to use with the scroller (it returns a `get` function and a couple more to insert/update/check size/etc), where ever I need to create a data source, I use my helper, the problem is that whenever I want to use the adapter (to insert/update/delete), I need to pass it to my helper (because it has the cached array which I would want to update as well), is there a nice way around that, can I inject it somehow instead?

I tried using `applyUpdates` with the adapter to insert items at start/end, but it didn't work, because applyUpdates removes the item and replaces it with the passed items, in order to insert at start of my array, I did something like this:

    adapter.applyUpdates(0, [newItem, cacheItems[0]]);

If I cause a refresh with `revision()`, it works (because it's re-reading from the cache array).

Is there a correct way to add items? 

Thanks

**Comment by jcstritt** [comment]
How can we made an insert at first position ? This replace the first item :

          return vm.adapter.applyUpdates(function (item, scope) {
            if (scope.$index === 1) {
              return [item, newItem];
            }
          });

And with this, first entry is deleted :

          return vm.adapter.applyUpdates(function (item, scope) {
            if (scope.$index === 1) {
              return [item, [newItem, item]];
            }
          });

**Comment by Madd0g** [comment]
I'll try with a function instead of the number, array. Thanks.

**Comment by mfeingold** [comment]
Either way function or index - if for a given item an update is given as an array of items, the original item is REPLACED by the items in the array. If the original item is also in the array, the DOM elements representing it will be removed and re-inserted

**Comment by jcstritt** [comment]
ok return [newItem, item] with fist index inserted the newItem, but it will not show because it is before the first index. 

I have an other question. In applyUpdates, can we know the length of internal buffer (the number it loops in applyUpdates ?

**Comment by Tsarpf** [comment]
Did anyone ever get this working? 

when I try
                obj.adapter.applyUpdates(function(item, scope) {
                    if(item.idx === EOF) {
                        return [item, msg];
                    }
                });

it should replace the last item with itself plus add a new one. I made sure the return statement was called once and once only, yet somehow some really random other element was replaced with the last one and the new one didn't appear. I'll look more into this tomorrow, but for now it really looks like the problem isn't in my code.

**Comment by mfeingold** [comment]
How idx is assigned and what is EOF? From what I know so far, the problem is that your condition `(idx === EOF)` turns true not where you expect it.
What exactly are you trying to accomplish here?

**Comment by Tsarpf** [comment]
http://plnkr.co/iVwmb9iUbxT8UODo5vKG?p=info

Tried to make a short example of it. What's happening here?

**Comment by mfeingold** [comment]
The difficulty is that whatever you are doing with apply updates has to be kept in sync with what your backed is supplying. Looking at the code it seems that this is wha you are trying to do, so it seems to be a bug. I will have a look at this today

**Comment by Tsarpf** [comment]
I tried the fix and now it works. Thanks and good job with both the fix and the library overall.
