### ISSUE TITLE
Bug when inserting, deleting at last position

### ISSUE THREAD

**Issue by jcstritt** [Hill30/NGScroller#78]
There is sure a bug when you :
1) insert at the end (entry not immediately visible)
2) delete last entry just inserted (already visible after delete)

**Comment by mfeingold** [comment]
What exactly is happening not to your expectations?

**Comment by jcstritt** [comment]
Perhaps not a bug. Can we know the buffer length to insert after the last ?

**Comment by mfeingold** [comment]
The buffer is built dynamically, its length changes as you scroll up and down. As you scroll up, the elements are trimmed from the bottom. They cam also be trimmed or added as the size of the viewport changes, or as the height of the visible elements change. It is very fluid. 

What exactly are you trying to do?

**Comment by jcstritt** [comment]
You can now test a plunker that test ui-scroll for CRUD operations :
http://plnkr.co/edit/uHhkEmES1uHQV1x5mCyg?p=preview

Update (+ 1'000.-- for amount) and delete are OK
Bug : after the FIRST run and if we add with first + button, we see the added entry (index 2) but no more the first entry. 
STOP and RUN once more :
Idem at last entry and after the FIRST run, if we add with the + button, nothing appears. 

If we scroll and internal buffer change, adding at first and last entry are ok.

Can you confirm. Thanks.

**Comment by mfeingold** [comment]
For some reason I cannot get your plunk to run. It gives me multuple 'undefined is not a function' erros when I try

**Comment by jcstritt** [comment]
OK, i'm a new user of plunker and have not understand all. So yet I have version 19 tested with Chrome, Safari and Firefox and my plunker is the same on all (slightly bootstrap buggy on Firefox, I don't know why).
http://plnkr.co/edit/uHhkEmES1uHQV1x5mCyg

**Comment by mfeingold** [comment]
Great, this one works. I will have a look

**Comment by mfeingold** [comment]
Have a look at my version of [your plunk](http://plnkr.co/edit/nbiOqqHHLl2o1ibtcC2q?p=preview). I commented out some redundant code and streamlined the rest. 

Keep in mind that I did not implement application of the modifications to the server data - it is not something easily done in a plunk. Without it as you scroll you will see some weird results - duplicate and missing rows, but once you implement it everything should work fine.

On a side note if you plan to use JQuery, scroll-jqlite.js is redundant, you can remove it from your page

**Comment by jcstritt** [comment]
Effectually, your plunk work. Thanks for your work. I think my error is the not use of index 0. I will try now to implement the concept with my server data. I close the issue if this work. Thank you very much.
