### ISSUE TITLE
negative requests from the service

### ISSUE THREAD

**Issue by ersingencturk** [Hill30/NGScroller#83]
I wonder what should we return from the service to the controller if negative values requested ? is this bug or by design ?

datasource.get = (index, count, success)->

i get requests for values like from the controller : 

request search results 1 24
request search results 25 24
request search results -23 24

first value is index , second one is count.

**Comment by mfeingold** [comment]
Negative values are to indicate items higher than the one which was supplied is the first one when the scroller was initialized. Look at this [example]( http://rawgit.com/Hill30/NGScroller/master/src/examples/persistentScroll.html). The number to the left is the index used to request the item, the number to the right is the index of the item in the dataset. Scroll it up and down, hit refresh and watch the numbers change.

HTH

**Comment by ersingencturk** [comment]
thanks for your fast response, great component btw, must come with angularjs by default instead of ng-repeat.

when I load the scrolling page I log these without scrolling or moving page position:

datasource.get asks for rows: index: 1 count: 24 
from my data array I return rows: 0 to 23
datasource.get asks for rows:  index:25 count: 24 (there are still empty areas on the page so it's fine to ask)
from my data array I return rows: 24 to 47 (not the whole page is full)
datasource.get asks for rows index:-23 count:24 (shouldn't be asking me this)
???? -> why is it asking me return 24 rows starting from -23??

at that point on the page I see 4 and a half rows on the screen with 6 columns each (same heights) total:24 boxes with 6 boxes half.

**Comment by ersingencturk** [comment]
here is the raw log if it makes sense:

2015-05-20 02:27:31.089 searchService.js:143 request search results 1 24 false
2015-05-20 02:27:31.243 searchService.js:170 afterload window user indexes: 0 23
2015-05-20 02:27:31.323 searchService.js:143 request search results 25 24 false
2015-05-20 02:27:31.349 searchService.js:170 afterload window user indexes: 24 47
2015-05-20 02:27:31.450 searchService.js:143 request search results -23 24 false

**Comment by mfeingold** [comment]
when the scroller is initialized (or refreshed) it starts with requesting <buffersize> items starting from index 1. If you return exactly buffsize items, it requests another batch, until there is no more space in the viewport or you return less than buffsize items indicating that there is no more items in this direction. Then the same process is repeated from the index 0 going upwards. 

Keep in mind that as you start scrolling the starting number can become anything depending on how you scroll or resize the viewport. Because of this calculating the response can be somewhat tricky. Check how it is done in one of the [examples](https://github.com/Hill30/NGScroller/blob/master/src/examples/persistentScroll.coffee) : 

							start = Math.max(-40, actualIndex)
							end = Math.min(actualIndex + count-1, 100)
							if (start > end)
								success([])
							else
								for i in [start..end]
									result.push "item #{i}"
								success(result)

**Comment by ersingencturk** [comment]
thanks this helped a lot. for anyone else having similar problems:

for negative values I used the solution from here: https://github.com/angular-ui/ui-utils/issues/319 from rajatrocks commented on Oct 28, 2014 

But my main issue turned out to be related to div clearing, since I was using float for divs inside ui-scroll , directive's top and bottom divs responsible for calculating the padding was not calculated correctly.

I solved this by wrapping directive with this and clearing the top and bottom divs created inside directive:

<style>
.clearlastandfirst div:first-of-type
{
    clear:both;
}
.clearlastandfirst div:last-of-type
{
    clear:both;
}

</style>
<div  class="clearlastandfirst">
<ui-scroll>
