### ISSUE TITLE
Keyboard scrolling stops in Chrome

### ISSUE THREAD

**Issue by compact** [Hill30/NGScroller#84]
When using the keyboard to scroll inside a `ui-scroll-viewport` element by pressing down arrow/Page Down/End etc, such as in [this demo](http://rawgit.com/Hill30/NGScroller/master/src/examples/scopeDatasource.html), the scrolling stops at some point and doesn't continue indefinitely. This happens in Chrome 42 and 43, only when using `ui-scroll-viewport` (no problem when the [window is the viewport](http://rawgit.com/Hill30/NGScroller/master/src/examples/windowviewport.html)), and only when the initial focus is on a child `ui-scroll` element (no problem if I manage to focus on the parent `ui-scroll-viewport` element, for example by clicking on the scrollbar). I think it's because the focus on the child element is lost when it gets destroyed after being scrolled out of view.

Firefox and IE don't have this issue.

Do you know if there's a way to fix this behaviour?

**Comment by mfeingold** [comment]
Thanx for reporting. We'll have a look

**Comment by dhilt** [comment]
I've made an investigation and a little demo with pure js logic: http://jsfiddle.net/dhilt/dmgz97c9/

It looks like an internal Chrome issue. Even when I try to simulate click or focus on some existed item after selected item is deleted... the scrolling stops anyway. I believe it's not a good idea to search a solution for a special browser case like a keyboard subscribing, manual events retriggering etc which unreasonably complicate the logic of the component...

So let's wait for what Google will say on it: https://code.google.com/p/chromium/issues/detail?id=493078

**Comment by dhilt** [comment]
Finally the fixed the issue in Chrome v104.
