### ISSUE TITLE
Scroll to index

### ISSUE THREAD

**Issue by blittle** [Hill30/NGScroller#85]
It would be really nice if there was a method on the adapter to scroll to a particular index.

**Comment by mfeingold** [comment]
Are you talking about something like [this](http://rawgit.com/Hill30/NGScroller/master/src/examples/positionedList.html)?

**Comment by Tsarpf** [comment]
I did something like this by changing an offset I'm keeping track of and incrementing the revision:
https://github.com/Tsarpf/Tsatter/blob/master/nodeapp/environment/public/js/services/infiniteMessages.js#L247

The code is bit of a mess, sorry for that. But basically it resets it to call getAroundLink with the offset set to obj.linkOffset.

**Comment by blittle** [comment]
Those examples work great. Implementing as such :+1:
