### ISSUE TITLE
Missing .js file referenced in bower.json

### ISSUE THREAD

**Issue by dsbaars** [Hill30/NGScroller#91]
You are referencing `build/scripts/scroll.js` in your bower.json, but it's not there. Probably because you added the build folder to your .gitignore file.

**Comment by dhilt** [comment]
And do you have any problems with it? As I know, the files listed within the "main" property are not actually used by Bower in any way, they are apparently there for the purpose of being used by other build tools. I.e. our 'grunt build' command creates build/scripts/scroll.js before tests running... I'm not sure I understand the definition of the main property, and what risks do you see on it?

**Comment by dsbaars** [comment]
Yes, it is used to automatically include the required files, by adding <link> and <script> includes. This does of course need the presence of already built files. 

Very useful, when you use LOTS of dependencies. 
For example, using:
- https://github.com/taptapship/wiredep
- https://github.com/klei/grunt-injector
- https://github.com/stephenplusplus/grunt-wiredep
- https://github.com/yeoman/grunt-bower-requirejs

**Comment by dhilt** [comment]
Done.
