### ISSUE TITLE
part of angular-ui

### ISSUE THREAD

**Issue by djindjic** [Hill30/NGScroller#92]
Is your directive still part of angular-ui? Followed link doesn't work:
https://github.com/angular-ui/ui-utils/tree/master/modules/scroll

**Comment by dhilt** [comment]
We are in the process of negotiations... Soon the directive will get its own repository within angular-ui (instead of angular-ui/ui-utils which is deprecated now).
Take a look at https://github.com/angular-ui/ui-utils/pull/406#issuecomment-119776352

**Comment by djindjic** [comment]
ok, but at this moment, can I download builded js file somewhere? I'm currently hacking it with your `grunt build` script.

**Comment by dhilt** [comment]
I've merged a PR https://github.com/Hill30/NGScroller/pull/94 an hour before your last reply, which changes the structure of repo and provides a direct access to js artifacts: https://github.com/Hill30/NGScroller/tree/master/dist

Also please note https://github.com/Hill30/NGScroller/blob/master/bower.json#L6

**Comment by djindjic** [comment]
Thanks!
