### ISSUE TITLE
Horizontal virtual scrolling?

### ISSUE THREAD

**Issue by Tagar** [Hill30/NGScroller#96]
Not sure if NGScroller provides horizontal scrolling too? 

Copying original issue from https://github.com/angular-ui/ui-grid/issues/6573

> Apache Zeppelin recently upgraded to ui-grid - that looks awesome btw!
> 
> What we're facing though is on wider datasets Chrome sometimes spends minutes to render a table.
> The table doesn't have a lot of data (it's very sparsely populated), so it seems just the number of columns is what important.
> 
> Maybe more of an extreme case - 5000 columns x 1000 rows recent Chrome spent 20-30 minutes to render on a decent PC. That's not a make-up case and we actually had to display such a wide sparsely populated table. (Our company normally deals with wider datasets)
> 
> Even on not so wide datasets we found browser rendering could be lagging..
> 
> What is a recommended size of dataset (in terms of number of columns, and number rows) that is know where ui-grid works well?
> 
> As an example, Cloudera HUE worked around displaying such wide datasets by adding "virtual" horizontal scrolling - basically columns are pushed to an html table only when they have to be visualized (if a user has pushed horizontal scrolling to the right .. and efficiently removing columns from html when they're not necessary for visualization). Cloudera Hue can render such wide datasets very quickly because browser has to render only a tiny subset of columns that it actually needs.
> 

Thanks!

**Comment by dhilt** [comment]
@Tagar The [ui-scroll](https://github.com/angular-ui/ui-scroll) has no horizontal scrolling feature ([ngx-ui-scroll](https://github.com/dhilt/ngx-ui-scroll) [does](https://dhilt.github.io/ngx-ui-scroll/#/#horizontal-mode)). Anyway it seems really difficult to virtualize both vertical and horizontal dimensions at the same time. If you need horizontal virtualization only than I would suggest to try to rotate the view (90°): 

**col1** data11 data21 data 31
**col2** data12 data22 data 32
...
**colN** data1N data2N data3N

Another workaround is to show, say, 15 columns by default and give an interface to hide/show columns separately from grid (this interface could be virtualized vertically).

**Comment by Tagar** [comment]
Thank you @dhilt 
I've updated https://issues.apache.org/jira/browse/ZEPPELIN-3251 with this information.
Unfortunately we'd need both horizontal and vertical scrolling at the same time, like it's implemented in Cloudera HUE for example (they don't use Angular though).
